name: Build

on: [push]

jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build the program
        run: pyinstaller -F -w main.py
      - name: Rename the artifact
        run : Rename-Item -Path "main.exe" -NewName "mo.exe"
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: mo
          path: mo.exe
